# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('Fog4VR', 
    	['Fog4VR', 'internet', 'wifi', 'buildings', 'applications', 'point-to-point','internet-apps'])
    obj.source = 'Fog4VR.cc'
    obj = bld.create_ns3_program('dash-migrationLTE-v2', 
    	['Fog4VR', 'internet', 'wifi', 'buildings', 'applications', 'point-to-point','internet-apps','lte','netanim'])
    obj.source = 'dash-migrationLTE-v2.cc'
